{% set version = "0.2.0" %}

package:
  name: pytest-beartype
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-beartype/pytest_beartype-{{ version }}.tar.gz
  sha256: 9eeec379f812e0e5c9c1bb7e95d90a33a79c387034f2d735e03bc9aa0fd7cf3f

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - beartype >=0.19.0
    - pytest
    - python >=3.8

test:
  source_files:
    - tests
  requires:
    - coverage
    - mypy
    - pip
    - pytest
  imports:
    - pytest_beartype
  commands:
    - pip check
    - mypy -p pytest_beartype

about:
  home: https://github.com/tusharsadhwani/pytest-beartype
  summary: Pytest plugin to run your tests with beartype checking enabled.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - tusharsadhwani
